import type { NextAuthOptions } from "next-auth";
import GoogleProvider from "next-auth/providers/google";
import CredentialsProvider from "next-auth/providers/credentials";

import { displayNameFromEmail, generatePersona } from "./personaGen";
import { verifyMagicLinkToken } from "./auth/magicLink";
import { touchUserOnSignIn } from "./users/touch";

const hasGoogle =
  !!process.env.GOOGLE_CLIENT_ID && !!process.env.GOOGLE_CLIENT_SECRET;

// When deployed at ai.thevrschool.org, we want the NextAuth session cookie
// scoped to .thevrschool.org so a future signed-in surface on the apex
// (vr-enrollment) can read the same identity (full SSO across the school
// within a school). Set NEXTAUTH_COOKIE_DOMAIN=.thevrschool.org in prod.
// Left undefined in dev/sof.ai-only deployments → NextAuth defaults to
// the request host (current behavior, no change).
const sharedCookieDomain = process.env.NEXTAUTH_COOKIE_DOMAIN || undefined;
const useSecureCookies =
  (process.env.NEXTAUTH_URL ?? "").startsWith("https://") ||
  process.env.NODE_ENV === "production";
const sessionCookieName = useSecureCookies
  ? "__Secure-next-auth.session-token"
  : "next-auth.session-token";

export const authOptions: NextAuthOptions = {
  session: { strategy: "jwt" },
  secret: process.env.NEXTAUTH_SECRET ?? "dev-insecure-secret-change-me",
  // Only override defaults when a shared domain is configured. Otherwise
  // NextAuth's host-only default keeps backwards compatibility for
  // deployments still served from sof.ai or localhost.
  ...(sharedCookieDomain
    ? {
        cookies: {
          sessionToken: {
            name: sessionCookieName,
            options: {
              httpOnly: true,
              sameSite: "lax" as const,
              path: "/",
              secure: useSecureCookies,
              domain: sharedCookieDomain,
            },
          },
        },
      }
    : {}),
  providers: [
    ...(hasGoogle
      ? [
          GoogleProvider({
            clientId: process.env.GOOGLE_CLIENT_ID!,
            clientSecret: process.env.GOOGLE_CLIENT_SECRET!,
          }),
        ]
      : []),
    // One-click guest entry. Zero fields required — the client calls
    // signIn("guest", { handle, displayName }) with values generated by
    // lib/personaGen so onboarding is effectively passwordless and <1s.
    CredentialsProvider({
      id: "guest",
      name: "Continue as guest",
      credentials: {
        handle: { label: "Handle", type: "text" },
        displayName: { label: "Display name", type: "text" },
      },
      async authorize(credentials) {
        // Always succeeds — if the client didn't send values, generate them
        // server-side so a bare signIn("guest") still works.
        const generated = generatePersona();
        const handle = credentials?.handle?.trim() || generated.handle;
        const displayName = credentials?.displayName?.trim() || generated.displayName;
        // CRITICAL: the stable user id must be globally unique. The handle
        // space (generatePersona) is ~29K combinations — birthday-paradox
        // collisions are ~50% likely after ~200 signups and would silently
        // mix progress/challenges/enrollments across different guests. Mint
        // a UUID as the account key; the handle stays for display only (it
        // can still collide across users without harm).
        const uniqueId = crypto.randomUUID();
        return {
          id: `guest:${uniqueId}`,
          email: `${handle}@guest.sof.ai`,
          name: displayName,
          image: null,
        };
      },
    }),
    // Magic-link path. The /signin form calls
    // POST /api/auth/magic-link/request to mint a token + email it via
    // Resend; the link in that email lands on /signin/magic which
    // signs in via this provider. The token is consumed (single-use,
    // expiring) inside FastAPI — see ``verifyMagicLinkToken``.
    CredentialsProvider({
      id: "magic-link",
      name: "Email magic link",
      credentials: {
        token: { label: "Token", type: "text" },
      },
      async authorize(credentials) {
        const token = credentials?.token?.trim();
        if (!token) return null;
        try {
          const email = await verifyMagicLinkToken(token);
          if (!email || !email.includes("@")) return null;
          const name = displayNameFromEmail(email);
          return {
            id: `email:${email}`,
            email,
            name,
            image: null,
          };
        } catch {
          // Surface as a generic auth failure; the /signin/magic page
          // reads the NextAuth error code and renders a friendlier
          // "this link is invalid or has expired" message.
          return null;
        }
      },
    }),
    // Dev-only one-shot email entry — same shape as the prior Credentials
    // provider but gated off in production so prod can never accept an
    // unverified email as a real identity. Magic-link is the production
    // path. Local development still gets a 0-friction email flow.
    ...(process.env.NODE_ENV !== "production"
      ? [
          CredentialsProvider({
            id: "email",
            name: "Email (dev only)",
            credentials: {
              email: { label: "Email", type: "email", placeholder: "you@sof.ai" },
            },
            async authorize(credentials) {
              const email = credentials?.email?.trim().toLowerCase();
              if (!email || !email.includes("@")) return null;
              const name = displayNameFromEmail(email);
              return {
                id: `email:${email}`,
                email,
                name,
                image: null,
              };
            },
          }),
        ]
      : []),
  ],
  pages: {
    signIn: "/signin",
  },
  callbacks: {
    // Best-effort: every successful sign-in upserts the shared
    // FastAPI ``UserProfile`` row so identity is unified across
    // sof.ai · www.thevrschool.org · ai.thevrschool.org. Returning
    // ``true`` unconditionally — failures are logged inside the helper
    // because sign-in must not break if the shared store is briefly
    // unreachable.
    async signIn({ user }) {
      // Belt-and-braces: ``touchUserOnSignIn`` is internally guarded
      // already, but a future change to it (or its transitive deps)
      // could throw before that try/catch is reached. NextAuth v4
      // treats a throwing ``signIn`` callback as a denied sign-in and
      // bounces to the error page — i.e. the entire auth surface goes
      // dark if the shared touch helper ever regresses. Wrap here so
      // ``return true`` is genuinely unconditional.
      try {
        await touchUserOnSignIn({
          email: user.email ?? "",
          name: user.name ?? null,
          image: user.image ?? null,
        });
      } catch (err) {
        console.warn("touchUserOnSignIn threw unexpectedly:", err);
      }
      return true;
    },
    async jwt({ token, user }) {
      if (user) {
        token.uid = user.id;
      }
      return token;
    },
    async session({ session, token }) {
      if (session.user && token.uid) {
        (session.user as { id?: string }).id = token.uid as string;
      }
      return session;
    },
  },
};

export const guestLoginEnabled = true;
export const emailLoginEnabled = true;
export const googleLoginEnabled = hasGoogle;
