import type { NextAuthOptions } from "next-auth";
import GoogleProvider from "next-auth/providers/google";
import CredentialsProvider from "next-auth/providers/credentials";

import { displayNameFromEmail, generatePersona } from "./personaGen";

const hasGoogle =
  !!process.env.GOOGLE_CLIENT_ID && !!process.env.GOOGLE_CLIENT_SECRET;

export const authOptions: NextAuthOptions = {
  session: { strategy: "jwt" },
  secret: process.env.NEXTAUTH_SECRET ?? "dev-insecure-secret-change-me",
  providers: [
    ...(hasGoogle
      ? [
          GoogleProvider({
            clientId: process.env.GOOGLE_CLIENT_ID!,
            clientSecret: process.env.GOOGLE_CLIENT_SECRET!,
          }),
        ]
      : []),
    // One-click guest entry. Zero fields required — the client calls
    // signIn("guest", { handle, displayName }) with values generated by
    // lib/personaGen so onboarding is effectively passwordless and <1s.
    CredentialsProvider({
      id: "guest",
      name: "Continue as guest",
      credentials: {
        handle: { label: "Handle", type: "text" },
        displayName: { label: "Display name", type: "text" },
      },
      async authorize(credentials) {
        // Always succeeds — if the client didn't send values, generate them
        // server-side so a bare signIn("guest") still works.
        const generated = generatePersona();
        const handle = credentials?.handle?.trim() || generated.handle;
        const displayName = credentials?.displayName?.trim() || generated.displayName;
        return {
          id: `guest:${handle}`,
          email: `${handle}@guest.sof.ai`,
          name: displayName,
          image: null,
        };
      },
    }),
    // Email path — just one field. Display name is auto-derived from the
    // local-part ("ada.lovelace@x.com" → "Ada Lovelace"); no second form
    // question. Still not production-auth (no magic link yet), but the UX
    // is intentionally one-liner.
    CredentialsProvider({
      id: "email",
      name: "Sign in with email",
      credentials: {
        email: { label: "Email", type: "email", placeholder: "you@sof.ai" },
      },
      async authorize(credentials) {
        const email = credentials?.email?.trim().toLowerCase();
        if (!email || !email.includes("@")) return null;
        const name = displayNameFromEmail(email);
        return {
          // Use the full normalized email as the stable identity. The
          // display handle is separately derived via handleFromEmail for
          // profile URLs; it intentionally discards the domain and is
          // not unique across domains, so it must not be used as an
          // account key.
          id: `email:${email}`,
          email,
          name,
          image: null,
        };
      },
    }),
  ],
  pages: {
    signIn: "/signin",
  },
  callbacks: {
    async jwt({ token, user }) {
      if (user) {
        token.uid = user.id;
      }
      return token;
    },
    async session({ session, token }) {
      if (session.user && token.uid) {
        (session.user as { id?: string }).id = token.uid as string;
      }
      return session;
    },
  },
};

export const guestLoginEnabled = true;
export const emailLoginEnabled = true;
export const googleLoginEnabled = hasGoogle;
