"""Seed the mitocwcourse table with a curated set of MIT OpenCourseWare courses.

All content is © MIT OpenCourseWare, licensed CC BY-NC-SA 4.0.
Canonical course pages live at https://ocw.mit.edu — the ``url`` field on each
row links there so every downstream artifact can carry attribution.

This seed is the *fast path*: it works offline and never hits the live API.
The live ingestion client in integrations/mit_ocw/client.py supplements it.
"""

from __future__ import annotations

import json

from sqlalchemy.exc import IntegrityError
from sqlmodel import Session, select

from .models import MitOcwCourse


_COURSES: list[dict] = [
    # ── Computer Science & Electrical Engineering (6.xxx) ─────────────────
    {
        "ocw_id": "ocw-6.006",
        "course_number": "6.006",
        "title": "Introduction to Algorithms",
        "description": "A rigorous introduction to algorithm design and analysis. Topics include sorting, searching, graph algorithms, dynamic programming, and NP-completeness.",
        "url": "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/",
        "thumbnail_url": "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/6-006s20.jpg",
        "department": "Electrical Engineering and Computer Science",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["Algorithms", "Data Structures", "Computer Science"]),
        "instructors_json": json.dumps(["Erik Demaine", "Jason Ku", "Justin Solomon"]),
        "semester": "Spring",
        "year": 2020,
        "has_video": True,
        "has_assignments": True,
        "school_approved": True,
    },
    {
        "ocw_id": "ocw-6.004",
        "course_number": "6.004",
        "title": "Computation Structures",
        "description": "Introduces architecture of digital systems. Topics include combinational/sequential circuits, finite-state machines, the von Neumann model, and the design of a RISC processor.",
        "url": "https://ocw.mit.edu/courses/6-004-computation-structures-spring-2017/",
        "thumbnail_url": "",
        "department": "Electrical Engineering and Computer Science",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["Computer Architecture", "Digital Systems", "Hardware"]),
        "instructors_json": json.dumps(["Silvina Hanono Wachman"]),
        "semester": "Spring",
        "year": 2017,
        "has_video": True,
        "has_assignments": True,
        "school_approved": True,
    },
    {
        "ocw_id": "ocw-6.009",
        "course_number": "6.009",
        "title": "Fundamentals of Programming",
        "description": "Introduces fundamental concepts of programming, including computation models, recursion, state, and object-oriented design. Labs involve Python-based projects.",
        "url": "https://ocw.mit.edu/courses/6-009-fundamentals-of-programming-spring-2020/",
        "thumbnail_url": "",
        "department": "Electrical Engineering and Computer Science",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["Python", "Programming", "Recursion", "Object-Oriented Design"]),
        "instructors_json": json.dumps(["Adam Hartz"]),
        "semester": "Spring",
        "year": 2020,
        "has_video": False,
        "has_assignments": True,
        "school_approved": True,
    },
    {
        "ocw_id": "ocw-6.042j",
        "course_number": "6.042J",
        "title": "Mathematics for Computer Science",
        "description": "Elementary discrete mathematics for computer science and engineering. Topics include formal logic, proofs, sets, functions, counting, probability, and graph theory.",
        "url": "https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-spring-2015/",
        "thumbnail_url": "",
        "department": "Electrical Engineering and Computer Science",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["Discrete Math", "Logic", "Probability", "Graph Theory"]),
        "instructors_json": json.dumps(["Albert Meyer", "Adam Chlipala"]),
        "semester": "Spring",
        "year": 2015,
        "has_video": True,
        "has_assignments": True,
        "school_approved": True,
    },
    {
        "ocw_id": "ocw-6.034",
        "course_number": "6.034",
        "title": "Artificial Intelligence",
        "description": "Surveys the key ideas and methods of AI: search, constraint satisfaction, knowledge representation, logic, planning, learning, neural networks, and probabilistic inference.",
        "url": "https://ocw.mit.edu/courses/6-034-artificial-intelligence-fall-2010/",
        "thumbnail_url": "",
        "department": "Electrical Engineering and Computer Science",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["Artificial Intelligence", "Machine Learning", "Search", "Planning"]),
        "instructors_json": json.dumps(["Patrick Winston"]),
        "semester": "Fall",
        "year": 2010,
        "has_video": True,
        "has_assignments": True,
        "school_approved": True,
    },
    {
        "ocw_id": "ocw-6.s191",
        "course_number": "6.S191",
        "title": "Introduction to Deep Learning",
        "description": "MIT's official introductory course on deep learning. Covers fundamentals of deep learning, applications in computer vision, NLP, and generative models.",
        "url": "https://ocw.mit.edu/courses/6-s191-introduction-to-deep-learning-january-iap-2020/",
        "thumbnail_url": "",
        "department": "Electrical Engineering and Computer Science",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["Deep Learning", "Neural Networks", "Computer Vision", "NLP"]),
        "instructors_json": json.dumps(["Alexander Amini", "Ava Soleimany"]),
        "semester": "January IAP",
        "year": 2020,
        "has_video": True,
        "has_assignments": True,
        "school_approved": True,
    },
    {
        "ocw_id": "ocw-6.858",
        "course_number": "6.858",
        "title": "Computer Systems Security",
        "description": "Design and implementation of secure computer systems. Covers security models, cryptography, buffer overflows, web security, network security, and side-channel attacks.",
        "url": "https://ocw.mit.edu/courses/6-858-computer-systems-security-fall-2014/",
        "thumbnail_url": "",
        "department": "Electrical Engineering and Computer Science",
        "level": "Graduate",
        "subjects_json": json.dumps(["Security", "Cryptography", "Systems", "Web Security"]),
        "instructors_json": json.dumps(["Nickolai Zeldovich", "James Mickens"]),
        "semester": "Fall",
        "year": 2014,
        "has_video": True,
        "has_assignments": True,
        "school_approved": True,
    },
    {
        "ocw_id": "ocw-6.033",
        "course_number": "6.033",
        "title": "Computer System Engineering",
        "description": "Topics on the engineering of computer software and hardware systems: techniques for controlling complexity, networks, operating systems, and security.",
        "url": "https://ocw.mit.edu/courses/6-033-computer-system-engineering-spring-2018/",
        "thumbnail_url": "",
        "department": "Electrical Engineering and Computer Science",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["Operating Systems", "Networks", "Distributed Systems", "Security"]),
        "instructors_json": json.dumps(["Katrina LaCurts"]),
        "semester": "Spring",
        "year": 2018,
        "has_video": False,
        "has_assignments": True,
        "school_approved": True,
    },
    # ── Mathematics (18.xxx) ───────────────────────────────────────────────
    {
        "ocw_id": "ocw-18.01sc",
        "course_number": "18.01SC",
        "title": "Single Variable Calculus",
        "description": "Differentiation and integration of functions of one variable, with applications. Covers limits, derivatives, chain rule, implicit differentiation, and integration techniques.",
        "url": "https://ocw.mit.edu/courses/18-01sc-single-variable-calculus-fall-2010/",
        "thumbnail_url": "",
        "department": "Mathematics",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["Calculus", "Derivatives", "Integration", "Mathematics"]),
        "instructors_json": json.dumps(["David Jerison"]),
        "semester": "Fall",
        "year": 2010,
        "has_video": True,
        "has_assignments": True,
        "school_approved": True,
    },
    {
        "ocw_id": "ocw-18.02sc",
        "course_number": "18.02SC",
        "title": "Multivariable Calculus",
        "description": "Differentiation and integration of functions of several variables, with applications in physics and engineering. Includes vector calculus, Green's theorem, and Stokes' theorem.",
        "url": "https://ocw.mit.edu/courses/18-02sc-multivariable-calculus-fall-2010/",
        "thumbnail_url": "",
        "department": "Mathematics",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["Multivariable Calculus", "Vector Calculus", "Mathematics"]),
        "instructors_json": json.dumps(["Denis Auroux"]),
        "semester": "Fall",
        "year": 2010,
        "has_video": True,
        "has_assignments": True,
        "school_approved": True,
    },
    {
        "ocw_id": "ocw-18.03sc",
        "course_number": "18.03SC",
        "title": "Differential Equations",
        "description": "Study of differential equations and linear algebra. Techniques include separation of variables, Laplace transforms, and systems of linear ODEs.",
        "url": "https://ocw.mit.edu/courses/18-03sc-differential-equations-fall-2011/",
        "thumbnail_url": "",
        "department": "Mathematics",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["Differential Equations", "Linear Algebra", "Mathematics"]),
        "instructors_json": json.dumps(["Haynes Miller", "Arthur Mattuck"]),
        "semester": "Fall",
        "year": 2011,
        "has_video": True,
        "has_assignments": True,
        "school_approved": True,
    },
    {
        "ocw_id": "ocw-18.06sc",
        "course_number": "18.06SC",
        "title": "Linear Algebra",
        "description": "A first course in linear algebra. Topics include matrices, linear systems, vector spaces, eigenvalues and eigenvectors, orthogonality, and the singular value decomposition.",
        "url": "https://ocw.mit.edu/courses/18-06sc-linear-algebra-fall-2011/",
        "thumbnail_url": "",
        "department": "Mathematics",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["Linear Algebra", "Matrices", "Eigenvalues", "Mathematics"]),
        "instructors_json": json.dumps(["Gilbert Strang"]),
        "semester": "Fall",
        "year": 2011,
        "has_video": True,
        "has_assignments": True,
        "school_approved": True,
    },
    {
        "ocw_id": "ocw-18.650",
        "course_number": "18.650",
        "title": "Statistics for Applications",
        "description": "Introduction to probability and statistics for data analysis. Covers hypothesis testing, regression, Bayesian inference, and nonparametric methods.",
        "url": "https://ocw.mit.edu/courses/18-650-statistics-for-applications-fall-2016/",
        "thumbnail_url": "",
        "department": "Mathematics",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["Statistics", "Probability", "Data Analysis", "Bayesian Methods"]),
        "instructors_json": json.dumps(["Philippe Rigollet"]),
        "semester": "Fall",
        "year": 2016,
        "has_video": True,
        "has_assignments": True,
        "school_approved": True,
    },
    {
        "ocw_id": "ocw-18.404j",
        "course_number": "18.404J",
        "title": "Theory of Computation",
        "description": "Mathematical introduction to the theory of computing. Finite automata, regular languages, context-free languages, Turing machines, computability, and complexity.",
        "url": "https://ocw.mit.edu/courses/18-404j-theory-of-computation-fall-2020/",
        "thumbnail_url": "",
        "department": "Mathematics",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["Theory of Computation", "Automata", "Complexity", "Turing Machines"]),
        "instructors_json": json.dumps(["Michael Sipser"]),
        "semester": "Fall",
        "year": 2020,
        "has_video": True,
        "has_assignments": True,
        "school_approved": True,
    },
    # ── Physics (8.xxx) ────────────────────────────────────────────────────
    {
        "ocw_id": "ocw-8.01sc",
        "course_number": "8.01SC",
        "title": "Classical Mechanics",
        "description": "Introduces classical mechanics: kinematics, Newton's laws, momentum, energy, rotation, oscillations, and gravity. Includes problem-solving workshops.",
        "url": "https://ocw.mit.edu/courses/8-01sc-classical-mechanics-fall-2016/",
        "thumbnail_url": "",
        "department": "Physics",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["Classical Mechanics", "Kinematics", "Newton's Laws", "Physics"]),
        "instructors_json": json.dumps(["Wit Busza", "Wade Fagen-Ulmschneider", "Sen-Ben Liao"]),
        "semester": "Fall",
        "year": 2016,
        "has_video": True,
        "has_assignments": True,
        "school_approved": True,
    },
    {
        "ocw_id": "ocw-8.02",
        "course_number": "8.02",
        "title": "Electricity and Magnetism",
        "description": "Electric fields, magnetic fields, electromagnetic induction, Maxwell's equations, and electromagnetic waves. Laboratory and problem-solving sessions included.",
        "url": "https://ocw.mit.edu/courses/8-02-electricity-and-magnetism-spring-2002/",
        "thumbnail_url": "",
        "department": "Physics",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["Electromagnetism", "Maxwell's Equations", "Physics"]),
        "instructors_json": json.dumps(["Walter Lewin"]),
        "semester": "Spring",
        "year": 2002,
        "has_video": True,
        "has_assignments": True,
        "school_approved": True,
    },
    {
        "ocw_id": "ocw-8.03sc",
        "course_number": "8.03SC",
        "title": "Physics III: Vibrations and Waves",
        "description": "Mechanical vibrations and waves, electromagnetic waves, optics, and an introduction to quantum mechanics via wave mechanics.",
        "url": "https://ocw.mit.edu/courses/8-03sc-physics-iii-vibrations-and-waves-fall-2016/",
        "thumbnail_url": "",
        "department": "Physics",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["Waves", "Optics", "Quantum Mechanics", "Physics"]),
        "instructors_json": json.dumps(["Yen-Jie Lee"]),
        "semester": "Fall",
        "year": 2016,
        "has_video": True,
        "has_assignments": True,
        "school_approved": True,
    },
    {
        "ocw_id": "ocw-8.04",
        "course_number": "8.04",
        "title": "Quantum Physics I",
        "description": "Experimental basis of quantum mechanics, wave functions, uncertainty principle, Schrödinger equation, and spin. Prepares students for advanced quantum mechanics.",
        "url": "https://ocw.mit.edu/courses/8-04-quantum-physics-i-spring-2016/",
        "thumbnail_url": "",
        "department": "Physics",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["Quantum Mechanics", "Schrödinger Equation", "Physics"]),
        "instructors_json": json.dumps(["Barton Zwiebach"]),
        "semester": "Spring",
        "year": 2016,
        "has_video": True,
        "has_assignments": True,
        "school_approved": True,
    },
    # ── Chemistry (5.xxx) ─────────────────────────────────────────────────
    {
        "ocw_id": "ocw-5.111sc",
        "course_number": "5.111SC",
        "title": "Principles of Chemical Science",
        "description": "Introduction to chemistry including: atomic structure, thermodynamics, chemical equilibrium, acid-base chemistry, electrochemistry, and kinetics.",
        "url": "https://ocw.mit.edu/courses/5-111sc-principles-of-chemical-science-fall-2014/",
        "thumbnail_url": "",
        "department": "Chemistry",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["General Chemistry", "Thermodynamics", "Equilibrium", "Kinetics"]),
        "instructors_json": json.dumps(["Catherine Drennan", "Elizabeth Vogel Taylor"]),
        "semester": "Fall",
        "year": 2014,
        "has_video": True,
        "has_assignments": True,
        "school_approved": True,
    },
    {
        "ocw_id": "ocw-5.60",
        "course_number": "5.60",
        "title": "Thermodynamics and Kinetics",
        "description": "Laws of thermodynamics, state functions, entropy, free energy, phase equilibrium, electrochemistry, chemical kinetics, and reaction mechanisms.",
        "url": "https://ocw.mit.edu/courses/5-60-thermodynamics-kinetics-spring-2008/",
        "thumbnail_url": "",
        "department": "Chemistry",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["Thermodynamics", "Kinetics", "Electrochemistry", "Chemistry"]),
        "instructors_json": json.dumps(["Robert Field"]),
        "semester": "Spring",
        "year": 2008,
        "has_video": True,
        "has_assignments": True,
        "school_approved": True,
    },
    # ── Biology (7.xxx) ───────────────────────────────────────────────────
    {
        "ocw_id": "ocw-7.01sc",
        "course_number": "7.01SC",
        "title": "Fundamentals of Biology",
        "description": "Introduction to biology: biochemistry, molecular biology, genetics, cell biology, and developmental biology. Emphasis on experimental approaches.",
        "url": "https://ocw.mit.edu/courses/7-01sc-fundamentals-of-biology-fall-2011/",
        "thumbnail_url": "",
        "department": "Biology",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["Molecular Biology", "Genetics", "Cell Biology", "Biochemistry"]),
        "instructors_json": json.dumps(["Eric Lander", "Robert Weinberg", "Tyler Jacks"]),
        "semester": "Fall",
        "year": 2011,
        "has_video": True,
        "has_assignments": True,
        "school_approved": True,
    },
    {
        "ocw_id": "ocw-7.014",
        "course_number": "7.014",
        "title": "Introductory Biology",
        "description": "Biochemistry, genetics, molecular biology, cell biology, developmental biology, plant biology, and ecology. Laboratory emphasis.",
        "url": "https://ocw.mit.edu/courses/7-014-introductory-biology-spring-2005/",
        "thumbnail_url": "",
        "department": "Biology",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["Biology", "Genetics", "Ecology", "Developmental Biology"]),
        "instructors_json": json.dumps(["Graham Walker", "Penny Chisholm"]),
        "semester": "Spring",
        "year": 2005,
        "has_video": False,
        "has_assignments": True,
        "school_approved": True,
    },
    # ── Mechanical Engineering (2.xxx) ────────────────────────────────────
    {
        "ocw_id": "ocw-2.001",
        "course_number": "2.001",
        "title": "Mechanics and Materials I",
        "description": "Statics, stress, strain, and elastic behavior of solids. Trusses, beams, and columns. Introduction to structural analysis and material properties.",
        "url": "https://ocw.mit.edu/courses/2-001-mechanics-materials-i-fall-2006/",
        "thumbnail_url": "",
        "department": "Mechanical Engineering",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["Statics", "Mechanics", "Materials Science", "Structural Analysis"]),
        "instructors_json": json.dumps(["Simona Socrate"]),
        "semester": "Fall",
        "year": 2006,
        "has_video": False,
        "has_assignments": True,
        "school_approved": True,
    },
    {
        "ocw_id": "ocw-2.003j",
        "course_number": "2.003J",
        "title": "Dynamics and Control I",
        "description": "Newton's laws, Lagrangian mechanics, vibrations, feedback control systems, and state-space methods for mechanical and electrical systems.",
        "url": "https://ocw.mit.edu/courses/2-003j-dynamics-and-control-i-fall-2007/",
        "thumbnail_url": "",
        "department": "Mechanical Engineering",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["Dynamics", "Control Systems", "Vibrations", "Lagrangian Mechanics"]),
        "instructors_json": json.dumps(["Neville Hogan"]),
        "semester": "Fall",
        "year": 2007,
        "has_video": False,
        "has_assignments": True,
        "school_approved": True,
    },
    {
        "ocw_id": "ocw-2.086",
        "course_number": "2.086",
        "title": "Numerical Computation for Mechanical Engineers",
        "description": "Numerical methods for mechanical engineers: linear algebra, ODEs, PDEs, and optimization. Projects in MATLAB.",
        "url": "https://ocw.mit.edu/courses/2-086-numerical-computation-for-mechanical-engineers-fall-2014/",
        "thumbnail_url": "",
        "department": "Mechanical Engineering",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["Numerical Methods", "MATLAB", "Simulation", "Engineering"]),
        "instructors_json": json.dumps(["Anthony Patera", "Masayuki Yano"]),
        "semester": "Fall",
        "year": 2014,
        "has_video": False,
        "has_assignments": True,
        "school_approved": True,
    },
    # ── Economics (14.xxx) ────────────────────────────────────────────────
    {
        "ocw_id": "ocw-14.01sc",
        "course_number": "14.01SC",
        "title": "Principles of Microeconomics",
        "description": "Supply, demand, consumer theory, production theory, market equilibrium, market structure, and welfare economics.",
        "url": "https://ocw.mit.edu/courses/14-01sc-principles-of-microeconomics-fall-2011/",
        "thumbnail_url": "",
        "department": "Economics",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["Microeconomics", "Supply and Demand", "Market Structure"]),
        "instructors_json": json.dumps(["Jonathan Gruber"]),
        "semester": "Fall",
        "year": 2011,
        "has_video": True,
        "has_assignments": True,
        "school_approved": True,
    },
    {
        "ocw_id": "ocw-14.02",
        "course_number": "14.02",
        "title": "Principles of Macroeconomics",
        "description": "GDP, unemployment, inflation, monetary and fiscal policy, international trade, exchange rates, and economic growth.",
        "url": "https://ocw.mit.edu/courses/14-02-principles-of-macroeconomics-fall-2009/",
        "thumbnail_url": "",
        "department": "Economics",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["Macroeconomics", "GDP", "Monetary Policy", "Fiscal Policy"]),
        "instructors_json": json.dumps(["Ricardo Caballero"]),
        "semester": "Fall",
        "year": 2009,
        "has_video": False,
        "has_assignments": True,
        "school_approved": True,
    },
    # ── Political Science (17.xxx) ─────────────────────────────────────────
    {
        "ocw_id": "ocw-17.20",
        "course_number": "17.20",
        "title": "Introduction to the American Political Process",
        "description": "The structure and operation of American political institutions: Congress, the presidency, bureaucracy, judiciary, parties, interest groups, and the media.",
        "url": "https://ocw.mit.edu/courses/17-20-introduction-to-the-american-political-process-spring-2004/",
        "thumbnail_url": "",
        "department": "Political Science",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["American Politics", "Congress", "Presidency", "Political Science"]),
        "instructors_json": json.dumps(["Andrea Campbell"]),
        "semester": "Spring",
        "year": 2004,
        "has_video": False,
        "has_assignments": True,
        "school_approved": True,
    },
    # ── Architecture (4.xxx) ───────────────────────────────────────────────
    {
        "ocw_id": "ocw-4.601",
        "course_number": "4.601",
        "title": "Introduction to Art History and Theory",
        "description": "Surveys art from antiquity through the contemporary period with an emphasis on methodological approaches: formalism, iconography, social history, and semiotics.",
        "url": "https://ocw.mit.edu/courses/4-601-introduction-to-art-history-and-theory-fall-2023/",
        "thumbnail_url": "",
        "department": "Architecture",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["Art History", "Architecture", "Visual Culture", "Theory"]),
        "instructors_json": json.dumps(["Caroline Jones"]),
        "semester": "Fall",
        "year": 2023,
        "has_video": False,
        "has_assignments": True,
        "school_approved": True,
    },
    {
        "ocw_id": "ocw-4.110",
        "course_number": "4.110",
        "title": "Design Across Scales",
        "description": "Studio course exploring design thinking from objects to cities. Students develop projects across multiple scales using computational and physical models.",
        "url": "https://ocw.mit.edu/courses/4-110-design-across-scales-spring-2020/",
        "thumbnail_url": "",
        "department": "Architecture",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["Design", "Urban Design", "Architecture", "Studio"]),
        "instructors_json": json.dumps(["Andres Sevtsuk"]),
        "semester": "Spring",
        "year": 2020,
        "has_video": False,
        "has_assignments": True,
        "school_approved": True,
    },
    # ── Philosophy (24.xxx) ───────────────────────────────────────────────
    {
        "ocw_id": "ocw-24.09",
        "course_number": "24.09",
        "title": "Minds and Machines",
        "description": "Philosophical introduction to the foundations of cognitive science. Topics: consciousness, mental representation, artificial intelligence, and personal identity.",
        "url": "https://ocw.mit.edu/courses/24-09-minds-and-machines-fall-2011/",
        "thumbnail_url": "",
        "department": "Linguistics and Philosophy",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["Philosophy of Mind", "Artificial Intelligence", "Cognitive Science"]),
        "instructors_json": json.dumps(["Alex Byrne"]),
        "semester": "Fall",
        "year": 2011,
        "has_video": False,
        "has_assignments": True,
        "school_approved": True,
    },
    # ── Earth, Atmospheric, and Planetary Sciences (12.xxx) ───────────────
    {
        "ocw_id": "ocw-12.340",
        "course_number": "12.340",
        "title": "Global Warming Science",
        "description": "Physical basis of global warming: greenhouse gases, climate sensitivity, feedbacks, ice cores, paleoclimate, and future projections.",
        "url": "https://ocw.mit.edu/courses/12-340-global-warming-science-fall-2012/",
        "thumbnail_url": "",
        "department": "Earth, Atmospheric, and Planetary Sciences",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["Climate Science", "Global Warming", "Atmospheric Science", "Environment"]),
        "instructors_json": json.dumps(["Kerry Emanuel"]),
        "semester": "Fall",
        "year": 2012,
        "has_video": False,
        "has_assignments": True,
        "school_approved": True,
    },
    # ── Writing (21W.xxx) ─────────────────────────────────────────────────
    {
        "ocw_id": "ocw-21w.031",
        "course_number": "21W.031",
        "title": "Science Writing and New Media",
        "description": "Teaches non-specialist writing about science and technology for general audiences. Students produce articles, essays, blogs, and multimedia presentations.",
        "url": "https://ocw.mit.edu/courses/21w-031-science-writing-and-new-media-spring-2016/",
        "thumbnail_url": "",
        "department": "Comparative Media Studies/Writing",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["Science Writing", "Journalism", "Media", "Communication"]),
        "instructors_json": json.dumps(["Alan Lightman"]),
        "semester": "Spring",
        "year": 2016,
        "has_video": False,
        "has_assignments": True,
        "school_approved": True,
    },
    # ── Linguistics (24.900) ──────────────────────────────────────────────
    {
        "ocw_id": "ocw-24.900",
        "course_number": "24.900",
        "title": "Introduction to Linguistics",
        "description": "What is language? Covers phonetics, phonology, morphology, syntax, semantics, and language acquisition. No prior linguistics background required.",
        "url": "https://ocw.mit.edu/courses/24-900-introduction-to-linguistics-fall-2012/",
        "thumbnail_url": "",
        "department": "Linguistics and Philosophy",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["Linguistics", "Syntax", "Semantics", "Phonology"]),
        "instructors_json": json.dumps(["Michel DeGraff"]),
        "semester": "Fall",
        "year": 2012,
        "has_video": False,
        "has_assignments": True,
        "school_approved": True,
    },
    # ── Management (15.xxx) ───────────────────────────────────────────────
    {
        "ocw_id": "ocw-15.390",
        "course_number": "15.390",
        "title": "New Enterprises",
        "description": "The theory and practice of starting new enterprises. Covers opportunity recognition, team building, financing, marketing, and growth.",
        "url": "https://ocw.mit.edu/courses/15-390-new-enterprises-spring-2013/",
        "thumbnail_url": "",
        "department": "Sloan School of Management",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["Entrepreneurship", "Startups", "Business", "Innovation"]),
        "instructors_json": json.dumps(["Bill Aulet"]),
        "semester": "Spring",
        "year": 2013,
        "has_video": False,
        "has_assignments": True,
        "school_approved": True,
    },
    {
        "ocw_id": "ocw-15.501",
        "course_number": "15.501",
        "title": "Introduction to Financial Accounting",
        "description": "Principles of financial accounting, financial statements, and accounting for assets, liabilities, and equity. Emphasis on analysis and interpretation.",
        "url": "https://ocw.mit.edu/courses/15-501-introduction-to-financial-accounting-spring-2004/",
        "thumbnail_url": "",
        "department": "Sloan School of Management",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["Accounting", "Finance", "Financial Statements", "Business"]),
        "instructors_json": json.dumps(["Sugata Roychowdhury"]),
        "semester": "Spring",
        "year": 2004,
        "has_video": False,
        "has_assignments": True,
        "school_approved": True,
    },
    # ── Electrical Engineering (6.003) ────────────────────────────────────
    {
        "ocw_id": "ocw-6.003",
        "course_number": "6.003",
        "title": "Signal Processing",
        "description": "Discrete-time and continuous-time signals and systems, Fourier transforms, Z-transforms, sampling, filtering, modulation, and feedback.",
        "url": "https://ocw.mit.edu/courses/6-003-signal-processing-fall-2011/",
        "thumbnail_url": "",
        "department": "Electrical Engineering and Computer Science",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["Signal Processing", "Fourier Analysis", "Systems", "Filtering"]),
        "instructors_json": json.dumps(["Dennis Freeman"]),
        "semester": "Fall",
        "year": 2011,
        "has_video": True,
        "has_assignments": True,
        "school_approved": True,
    },
    # ── Health Sciences (HST.xxx) ─────────────────────────────────────────
    {
        "ocw_id": "ocw-hst.508",
        "course_number": "HST.508",
        "title": "Genomics and Computational Biology",
        "description": "Computational approaches to analyzing genomic data: sequence alignment, gene finding, genome assembly, phylogenetics, and systems biology.",
        "url": "https://ocw.mit.edu/courses/hst-508-genomics-and-computational-biology-fall-2002/",
        "thumbnail_url": "",
        "department": "Health Sciences and Technology",
        "level": "Graduate",
        "subjects_json": json.dumps(["Genomics", "Computational Biology", "Bioinformatics", "Systems Biology"]),
        "instructors_json": json.dumps(["Christopher Burge", "David Gifford", "Tommi Jaakkola"]),
        "semester": "Fall",
        "year": 2002,
        "has_video": False,
        "has_assignments": True,
        "school_approved": True,
    },
    # ── Urban Studies (11.xxx) ────────────────────────────────────────────
    {
        "ocw_id": "ocw-11.188",
        "course_number": "11.188",
        "title": "Urban Planning and Social Science Laboratory",
        "description": "GIS, data analysis, and social science methods applied to urban problems. Students conduct original research on cities and neighborhoods.",
        "url": "https://ocw.mit.edu/courses/11-188-urban-planning-and-social-science-laboratory-spring-2015/",
        "thumbnail_url": "",
        "department": "Urban Studies and Planning",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["Urban Planning", "GIS", "Data Analysis", "Social Science"]),
        "instructors_json": json.dumps(["Joseph Ferreira"]),
        "semester": "Spring",
        "year": 2015,
        "has_video": False,
        "has_assignments": True,
        "school_approved": True,
    },
    # ── Media Arts (CMS.xxx) ──────────────────────────────────────────────
    {
        "ocw_id": "ocw-cms.300",
        "course_number": "CMS.300",
        "title": "Introduction to Videogame Studies",
        "description": "History, aesthetics, and theory of video games. Students analyze games as cultural objects, design game projects, and explore games and learning.",
        "url": "https://ocw.mit.edu/courses/cms-300-introduction-to-videogame-studies-fall-2011/",
        "thumbnail_url": "",
        "department": "Comparative Media Studies/Writing",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["Game Design", "Media Studies", "Game Theory", "Digital Media"]),
        "instructors_json": json.dumps(["Jesper Juul"]),
        "semester": "Fall",
        "year": 2011,
        "has_video": False,
        "has_assignments": True,
        "school_approved": True,
    },
    # ── Aeronautics and Astronautics (16.xxx) ────────────────────────────
    {
        "ocw_id": "ocw-16.00",
        "course_number": "16.00",
        "title": "Introduction to Aerospace Engineering and Design",
        "description": "Fundamental concepts of aeronautics and astronautics: lift, drag, propulsion, orbital mechanics, and spacecraft design. Includes lab projects.",
        "url": "https://ocw.mit.edu/courses/16-00-introduction-to-aerospace-engineering-and-design-spring-2003/",
        "thumbnail_url": "",
        "department": "Aeronautics and Astronautics",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["Aerospace Engineering", "Aerodynamics", "Orbital Mechanics", "Spacecraft"]),
        "instructors_json": json.dumps(["Sheila Widnall"]),
        "semester": "Spring",
        "year": 2003,
        "has_video": False,
        "has_assignments": True,
        "school_approved": True,
    },
    # ── Civil Engineering (1.xxx) ─────────────────────────────────────────
    {
        "ocw_id": "ocw-1.00",
        "course_number": "1.00",
        "title": "Introduction to Computers and Engineering Problem Solving",
        "description": "Computational tools for civil/environmental engineers. Java programming, numerical methods, simulation, databases, and web-based applications.",
        "url": "https://ocw.mit.edu/courses/1-00-introduction-to-computers-and-engineering-problem-solving-spring-2012/",
        "thumbnail_url": "",
        "department": "Civil and Environmental Engineering",
        "level": "Undergraduate",
        "subjects_json": json.dumps(["Programming", "Java", "Engineering", "Simulation"]),
        "instructors_json": json.dumps(["George Kocur"]),
        "semester": "Spring",
        "year": 2012,
        "has_video": False,
        "has_assignments": True,
        "school_approved": True,
    },
]


def seed(session: Session) -> int:
    """Upsert curated MIT OCW courses. Returns count of rows created."""
    created = 0
    for data in _COURSES:
        existing = session.exec(
            select(MitOcwCourse).where(MitOcwCourse.ocw_id == data["ocw_id"])
        ).first()
        if existing:
            continue
        session.add(MitOcwCourse(**data))
        created += 1
    try:
        session.commit()
    except IntegrityError:
        session.rollback()
    return created
